### ISSUE TITLE
Add KFunc pages

### ISSUE THREAD

**Issue by dylandreimerink** [isovalent/ebpf-docs#3]
Kfuncs (kernel functions) are the new replacement for helper functions, as such we should start documenting these as well. Doing so is slightly more challenging since there are no man-page docs for these that we can reuse yet. 

```[tasklist]
### Tasks
- [x] Add a linux/concepts page for kfuncs to go into depth on how to use them
- [x] Add a section to the "eBPF on Linux" page
- [x] Add index of kfunc programs sorted by type (comparable to helper functions)
- [x] Add tooling to generate kfunc -> program type
- [x] Add kfuncs to feature-version.yaml
- [x] Add kfuncs to quick links
- [x] Add tooling to generate function signatures (possible via vmlinux BTF blobs)
- [x] Add pages for known kfuncs, attempt to write a little context if possible
- [x] Add tooling to generate program type -> kfunc lists
```
