### ISSUE TITLE
Add more concept explainers

### ISSUE THREAD

**Issue by dylandreimerink** [isovalent/ebpf-docs#6]
I have recently come across a lot of "concepts" (features / systems) that could use their own page. Such a page is good for a coherent explanation of a concept and also a location to link to from other pages. This issue is just a place to get this out of my head, will make into separate issues later:

```[tasklist]
### Tasks
- [ ] BPF trampolines (https://lwn.net/Articles/804937/)
- [ ] BPF-to-BPF functions (https://github.com/torvalds/linux/commit/cc8b0b92a1699bc32f7fec71daa2bfc90de43a4d)
- [ ] dynptrs (https://lwn.net/Articles/895885/)
- [ ] kptrs (Kernel pointers) (https://lwn.net/Articles/907129/)
- [ ] Custom datastructures (https://github.com/torvalds/linux/commit/958cf2e273f0929c66169e0788031310e8118722)
- [ ] Open coded iterators (https://lore.kernel.org/all/20230308184121.1165081-4-andrii@kernel.org/#r)
- [ ] Fentry hooks (https://github.com/torvalds/linux/commit/a319185be9f5ad13c2a296d448ac52ffe45d194c)
```
